### ISSUE TITLE
VS 2013 Support

### ISSUE THREAD

**Issue by Kamek** [ishani/ClangVSx#16]
Will this work with the new 2013 version of Visual Studio? I'm kind of stuck using the new version for work but would rather use clang.

**Comment by ishani** [comment]
FWIW, latest ClangVSx has full 2013 support (check my site for more info)

**Comment by locfso123** [comment]
dowloaded:
http://llvm.org/releases/3.4/LLVM-3.4-win32.exe
but nothing invisible vs 2013

**Comment by locfso123** [comment]
how to compiler code from LLVM-3.4-win32.exe ????
step by step
