### ISSUE TITLE
VS110COMNTOOLS ENV Variable in CVXBuildSystem.cs does not give proper path

### ISSUE THREAD

**Issue by MichaelMitchellM** [ishani/ClangVSx#18]
I have VS2013 on a seperate HDD, not sure if that is the issue, but the short of it is the lib.exe and link.exe are not being pathed too.

I manually went in and added my path to VS2013 in place of the path gotten from VS110COMNTOOLS and then built the solution and it now works.

I recommend a short term fix of adding an optional user input for the folder path of their VS2013 in the option window opened from the clang menu.

Thank you for making this!

**Comment by ishani** [comment]
Can now override the envvars in the Settings panel
