### ISSUE TITLE
Compilation should not stop after 5 errors

### ISSUE THREAD

**Issue by danielkeller** [ishani/ClangVSx#20]
I use ClangVSx to get better error messages, and to diagnose msvc crashes. I also use exceptions in my program, which clang can't compile. So, there were more than 5 files that didn't compile, and ClangVSx stopped compiling before getting to the real problem, and without telling me why (I had to open it in the debugger to find what was wrong.)

So, it would be very helpful to have a "More than x errors, stopping compilation" message. Personally I would just disable this feature, since most build systems don't have it.

**Comment by tpoechtrager** [comment]
Clang 3.7 (trunk) has exception support for Windows x64,
if you want to give it a try: http://llvm.org/builds/.

**Comment by ishani** [comment]
Have just pushed changes to let that hard-coded 5 limit be changed in the settings. Set to 0 to never abandon. + it will now always tell you if it's abandoned the build due to hitting the limit.
