### ISSUE TITLE
VS 2015 addin support

### ISSUE THREAD

**Issue by Enamex** [ishani/ClangVSx#21]
If I'm not mistaken, VS addin support is getting dropped for VS 2015 (doesn't work in RC already); what are the plans, if any, to port this to a VS extension?

Or is the add-in getting dropped completely for the native support that's been rumored to be coming for Windows development with Clang on VS (not the mobile development that's already in RC) ?

**Comment by LegalizeAdulthood** [comment]
:+1:

**Comment by ishani** [comment]
I haven't looked at a VSIX port yet; may require some substantial refactoring and as such I should probably find a way to make the whole thing more useful, perhaps as a more generic vcproj-to-whatever translation shim .. like running PC-lint, or whatnot. 

For now it'll just be 2013 supported until I have time to dig into 2015 properly .. or until a native Clang toolchain for Windows drops into 2015 and makes the decision easier :)
