### ISSUE TITLE
ClangVSx Cannot Find lib.exe

### ISSUE THREAD

**Issue by LukeMauldin** [ishani/ClangVSx#7]
I have installed the most recent version of ClangVSx and the prebuilt Christmas 2012 of Clang.  I have tested Clang manually from the command prompt and it works.  When I try to build a project in Visual Studio using Clang, I get the following error:
Could not find lib.exe, check ClangVSx Settings - tried:
C:\Program Files(x86)\Microsoft Visual Studio 11.0\VC\bin\lib.exe

However, I installed Visual Studio to a different location:
E:\Programs\VisualStudio2012\
The lib.exe file is present in E:\Programs\VisualStudio2012\VC\bin
How can I configure ClangVSx to look in the correct location?

**Comment by ishani** [comment]
just pushed options in Settings for overriding the root path
